### ISSUE TITLE
No option to prevent some css rules from being flipped

### ISSUE THREAD

**Issue by sarahmurray** [twbs/grunt-css-flip#29]
This was a feature of css-flip: https://github.com/twitter/css-flip#noflip.

Any chance it could be built into this plugin?

**Comment by cvrebert** [comment]
It still **is** a feature of css-flip, no?
`@noflip` is a directive that goes in the CSS source itself, it's not a configuration option of css-flip, and hence not of this grunt plugin.
See also https://github.com/twitter/css-flip/blob/master/bin/css-flip#L12

**Comment by sarahmurray** [comment]
Thanks - I just worked out it is being removed during less compiling, so not related to this plugin.
